baseURL = "https://bingdian.im/"
languageCode = "zh-cn"
title = "On The Way"
theme = "lite"
disqusShortname = "bingdian-im"
googleAnalytics = "UA-1245097-20"

[params]
  description = "爱折腾，爱生活..."
  mainSections = ["posts", "read", "develop", "photography"]

[Menus]
  main = [
      {Name = "Tags", URL = "/tags/index.html", Weight = 1},
      {Name = "Github", URL = "https://github.com/bingdian", Weight = 2},
      {Name = "About", URL = "/about/index.html", Weight = 3}
  ]

[markup.goldmark.renderer]
	unsafe= true

[outputFormats]
  [outputFormats.MANIFEST]
    name = "manifest"
    baseName = "manifest"
    mediaType = "application/json"
    rel = "manifest"

[outputs]
    home  = [ "HTML",  "MANIFEST", "SITEMAP"]
