baseURL = "https://bingdian.io/"
languageCode = "zh-cn"
title = "On The Way"
theme = "lite"
disqusShortname = "bingdian-im"
googleAnalytics = "UA-1245097-20"

[params]
  description = "爱折腾，爱生活..."
  mainSections = ["posts", "read", "develop"]

[Menus]
  main = [
      {Name = "PROJECTS", URL = "/projects/"},
      {Name = "ABOUT", URL = "/about/index.html"}
  ]

[markup.goldmark.renderer]
	unsafe= true

[outputFormats]
  [outputFormats.MANIFEST]
    name = "manifest"
    baseName = "manifest"
    mediaType = "application/json"
    rel = "manifest"

[outputs]
    home  = [ "HTML",  "MANIFEST", "SITEMAP"]
